# Generated by Django 3.0.7 on 2021-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=10)),
                ('answers', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=100)),
            ],
        ),
    ]
