# Generated by Django 3.0.7 on 2021-07-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='correctAnswer',
        ),
    ]
